### ISSUE TITLE
Java 8 version for 1.16?

### ISSUE THREAD

**Issue by t0mtee** [wutdahack/BedBenefitsFabric#1]

**Comment by wutdahack** [comment]
what do you mean by this? the 1.16 version can work on java 8.

**Comment by wutdahack** [comment]
as there has been no reply, i am going to assume that the issue has been resolved.

**Comment by t0mtee** [comment]
oh sorry, i didn't reply in time. when i try to launch the 1.16 version on java 8, it doesn't work for me. maybe i had the 1.17 version but i doubt that

**Comment by wutdahack** [comment]
oh that's okay, are you using the 1.16.5-0.1.1 version?
